/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        display: ["Fraunces", "Georgia", "serif"],
      },
      colors: {
        canvas: "var(--bg-canvas)",
        surface: "var(--bg-surface)",
        "surface-2": "var(--bg-surface-2)",
        "surface-3": "var(--bg-surface-3)",
        ink: "var(--text-primary)",
        sub: "var(--text-secondary)",
        muted: "var(--text-muted)",
        brand: "var(--text-brand)",
        accent: "var(--color-primary)",
        "accent-soft": "var(--forest-50)",
        "accent-muted": "var(--forest-100)",
        border: "var(--border-subtle)",
        "border-default": "var(--border-default)",
        "border-brand": "var(--border-brand)",
        sand: "var(--sand-50)",
        "sand-deep": "var(--sand-100)",
        forest: "var(--forest-900)",
        "forest-mid": "var(--forest-800)",
        "forest-500": "var(--forest-500)",
        "forest-50": "var(--forest-50)",
        warning: "var(--amber-500)",
        "warning-bg": "var(--amber-50)",
        error: "var(--red-500)",
        success: "var(--success-500)",
        "success-bg": "var(--success-50)",
        live: "var(--status-live)",
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      borderRadius: {
        card: "var(--card-radius)",
        "card-sm": "var(--card-radius-sm)",
        btn: "var(--button-radius)",
        input: "var(--input-radius)",
        chip: "var(--chip-radius)",
        modal: "var(--modal-radius)",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        DEFAULT: "var(--duration-default)",
        moderate: "var(--duration-moderate)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        out: "var(--ease-out)",
        "in-out": "var(--ease-in-out)",
        spring: "var(--ease-spring)",
        decel: "var(--ease-decel)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(24px)" },
        },
        pulseLive: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        searchRing: {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(1.8)", opacity: "0.2" },
        },
      },
      animation: {
        "fade-up": "fade-up 500ms var(--ease-out) forwards",
        shimmer: "shimmer 1.4s ease-in-out infinite",
        "slide-up": "slide-up 300ms var(--ease-out) forwards",
        "pulse-live": "pulseLive 2s ease-in-out infinite",
        "search-ring": "searchRing 2.4s ease-out infinite",
      },
      maxWidth: {
        content: "var(--content-max-width)",
      },
    },
  },
  plugins: [],
};
